/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Logins;

import java.awt.Component;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    DBCon c = new DBCon();
    public Login() {
        initComponents();
        pnlwellcome.show();
        pnllogin.hide();
        pnlSign.hide();
         
    }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        pnlSign = new javax.swing.JPanel();
        lblscross = new javax.swing.JLabel();
        lblsignup = new javax.swing.JLabel();
        lblsusername = new javax.swing.JLabel();
        txtspass = new javax.swing.JTextField();
        lblspass = new javax.swing.JLabel();
        txtsuser = new javax.swing.JTextField();
        lblsemail = new javax.swing.JLabel();
        txtsemail = new javax.swing.JTextField();
        lblscontact = new javax.swing.JLabel();
        txtscontact = new javax.swing.JTextField();
        btnssignin = new javax.swing.JButton();
        btncancelsign = new javax.swing.JButton();
        pnllogin = new javax.swing.JPanel();
        lbllogin = new javax.swing.JLabel();
        lblclosedlogin = new javax.swing.JLabel();
        lblpasswordlogin = new javax.swing.JLabel();
        lbluserlogin = new javax.swing.JLabel();
        txtUserNamelogin = new javax.swing.JTextField();
        btlloginclear = new javax.swing.JButton();
        btnsignup = new javax.swing.JButton();
        txtPasswordlogin = new javax.swing.JPasswordField();
        btnlogin1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        pnlwellcome = new javax.swing.JPanel();
        lblwellcome = new javax.swing.JLabel();
        lalclgimg = new javax.swing.JLabel();
        lblloginbtn = new javax.swing.JLabel();

        jButton2.setText("jButton2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1400, 800));
        getContentPane().setLayout(null);

        pnlSign.setBackground(new java.awt.Color(153, 153, 255));
        pnlSign.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(1, 1, 1), 2));
        pnlSign.setLayout(null);

        lblscross.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblscross.setText("X");
        lblscross.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblscrossMouseClicked(evt);
            }
        });
        pnlSign.add(lblscross);
        lblscross.setBounds(310, 10, 20, 40);

        lblsignup.setFont(new java.awt.Font("Algerian", 1, 36)); // NOI18N
        lblsignup.setText("Sign Up");
        lblsignup.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        pnlSign.add(lblsignup);
        lblsignup.setBounds(90, 70, 150, 50);

        lblsusername.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblsusername.setText("Username :");
        pnlSign.add(lblsusername);
        lblsusername.setBounds(60, 150, 170, 30);

        txtspass.setBackground(new java.awt.Color(153, 153, 255));
        txtspass.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        txtspass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtspassActionPerformed(evt);
            }
        });
        pnlSign.add(txtspass);
        txtspass.setBounds(110, 460, 200, 30);

        lblspass.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblspass.setText("Password :");
        pnlSign.add(lblspass);
        lblspass.setBounds(60, 420, 160, 30);

        txtsuser.setBackground(new java.awt.Color(153, 153, 255));
        txtsuser.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        txtsuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsuserActionPerformed(evt);
            }
        });
        pnlSign.add(txtsuser);
        txtsuser.setBounds(110, 190, 200, 30);

        lblsemail.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblsemail.setText("Email :");
        pnlSign.add(lblsemail);
        lblsemail.setBounds(60, 240, 160, 30);

        txtsemail.setBackground(new java.awt.Color(153, 153, 255));
        txtsemail.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        txtsemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsemailActionPerformed(evt);
            }
        });
        pnlSign.add(txtsemail);
        txtsemail.setBounds(110, 280, 200, 30);

        lblscontact.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblscontact.setText("Contact :");
        pnlSign.add(lblscontact);
        lblscontact.setBounds(60, 330, 160, 30);

        txtscontact.setBackground(new java.awt.Color(153, 153, 255));
        txtscontact.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        txtscontact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtscontactActionPerformed(evt);
            }
        });
        pnlSign.add(txtscontact);
        txtscontact.setBounds(110, 370, 200, 30);

        btnssignin.setBackground(new java.awt.Color(153, 153, 255));
        btnssignin.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnssignin.setText("Sign Up");
        btnssignin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        btnssignin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnssigninActionPerformed(evt);
            }
        });
        pnlSign.add(btnssignin);
        btnssignin.setBounds(50, 550, 100, 50);

        btncancelsign.setBackground(new java.awt.Color(153, 153, 255));
        btncancelsign.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btncancelsign.setText("Cancel ");
        btncancelsign.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        btncancelsign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelsignActionPerformed(evt);
            }
        });
        pnlSign.add(btncancelsign);
        btncancelsign.setBounds(200, 550, 100, 50);

        getContentPane().add(pnlSign);
        pnlSign.setBounds(1000, 0, 600, 800);

        pnllogin.setBackground(new java.awt.Color(255, 102, 102));
        pnllogin.setLayout(null);

        lbllogin.setFont(new java.awt.Font("Algerian", 1, 36)); // NOI18N
        lbllogin.setText("Login");
        lbllogin.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        pnllogin.add(lbllogin);
        lbllogin.setBounds(120, 80, 110, 40);

        lblclosedlogin.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblclosedlogin.setText("X");
        lblclosedlogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblclosedloginMouseClicked(evt);
            }
        });
        pnllogin.add(lblclosedlogin);
        lblclosedlogin.setBounds(320, 10, 20, 30);

        lblpasswordlogin.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblpasswordlogin.setText("Password :");
        pnllogin.add(lblpasswordlogin);
        lblpasswordlogin.setBounds(50, 260, 170, 40);

        lbluserlogin.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbluserlogin.setText("Username :");
        pnllogin.add(lbluserlogin);
        lbluserlogin.setBounds(50, 160, 170, 40);

        txtUserNamelogin.setBackground(new java.awt.Color(255, 102, 102));
        txtUserNamelogin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        txtUserNamelogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUserNameloginActionPerformed(evt);
            }
        });
        pnllogin.add(txtUserNamelogin);
        txtUserNamelogin.setBounds(110, 210, 220, 40);

        btlloginclear.setBackground(new java.awt.Color(204, 0, 0));
        btlloginclear.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btlloginclear.setText("Clear");
        btlloginclear.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btlloginclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btlloginclearActionPerformed(evt);
            }
        });
        pnllogin.add(btlloginclear);
        btlloginclear.setBounds(140, 460, 100, 40);

        btnsignup.setBackground(new java.awt.Color(204, 0, 0));
        btnsignup.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnsignup.setText("Sign Up");
        btnsignup.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnsignup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsignupActionPerformed(evt);
            }
        });
        pnllogin.add(btnsignup);
        btnsignup.setBounds(220, 410, 100, 40);

        txtPasswordlogin.setBackground(new java.awt.Color(255, 102, 102));
        txtPasswordlogin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        txtPasswordlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordloginActionPerformed(evt);
            }
        });
        pnllogin.add(txtPasswordlogin);
        txtPasswordlogin.setBounds(110, 310, 220, 40);

        btnlogin1.setBackground(new java.awt.Color(204, 0, 0));
        btnlogin1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnlogin1.setText("Login");
        btnlogin1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnlogin1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlogin1ActionPerformed(evt);
            }
        });
        pnllogin.add(btnlogin1);
        btnlogin1.setBounds(60, 410, 100, 40);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("OR");
        jLabel1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        pnllogin.add(jLabel1);
        jLabel1.setBounds(180, 420, 30, 20);

        getContentPane().add(pnllogin);
        pnllogin.setBounds(1000, 0, 600, 800);

        pnlwellcome.setBackground(new java.awt.Color(0, 102, 102));
        pnlwellcome.setBorder(new javax.swing.border.MatteBorder(null));
        pnlwellcome.setForeground(new java.awt.Color(255, 153, 255));
        pnlwellcome.setLayout(null);

        lblwellcome.setFont(new java.awt.Font("Algerian", 1, 55)); // NOI18N
        lblwellcome.setForeground(new java.awt.Color(240, 240, 240));
        lblwellcome.setText("Wellcome...!");
        lblwellcome.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(240, 240, 240)));
        pnlwellcome.add(lblwellcome);
        lblwellcome.setBounds(350, 40, 380, 76);

        lalclgimg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/clg.jpg"))); // NOI18N
        pnlwellcome.add(lalclgimg);
        lalclgimg.setBounds(10, 140, 980, 530);

        lblloginbtn.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblloginbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/login (1).png"))); // NOI18N
        lblloginbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblloginbtnMouseClicked(evt);
            }
        });
        pnlwellcome.add(lblloginbtn);
        lblloginbtn.setBounds(1110, 20, 50, 40);

        getContentPane().add(pnlwellcome);
        pnlwellcome.setBounds(10, 0, 1360, 700);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblloginbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblloginbtnMouseClicked
        // TODO add your handling code here:
        pnllogin.show();
       // pnlwellcome.hide();
    }//GEN-LAST:event_lblloginbtnMouseClicked

    private void lblclosedloginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblclosedloginMouseClicked
        // TODO add your handling code here:
        pnllogin.hide();
    }//GEN-LAST:event_lblclosedloginMouseClicked

    private void lblscrossMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblscrossMouseClicked
        // TODO add your handling code here:
        pnlSign.hide();
    }//GEN-LAST:event_lblscrossMouseClicked

    private void txtspassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtspassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtspassActionPerformed

    private void txtsuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsuserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsuserActionPerformed

    private void txtsemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsemailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsemailActionPerformed

    private void txtscontactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtscontactActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtscontactActionPerformed

    private void btnssigninActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnssigninActionPerformed
        // TODO add your handling code here:
      c.nonSelect("INSERT INTO `sign_up`(`username`, `email`, `contact`, `password`) VALUES ('"+txtsuser.getText()+"','"+txtsemail.getText()+"','"+txtscontact.getText()+"','"+txtspass.getText()+"')");
      if(txtsuser.getText().toString().isEmpty()){
          JOptionPane.showMessageDialog(pnlSign, "Please Enter Username!!!");
      } 
      else
          if(txtsemail.getText().toString().isEmpty()){
          JOptionPane.showMessageDialog(pnlSign, "Please Enter Email-ID!!!");
      } 
      else
          if(txtscontact.getText().toString().isEmpty()){
          JOptionPane.showMessageDialog(pnlSign, "Please Enter Contact No.!!!");
      } 
      else
          if(txtspass.getText().toString().isEmpty()){
          JOptionPane.showMessageDialog(pnlSign, "Please Enter Password!!!");
      } 
          else{
              JOptionPane.showMessageDialog(null, "Successfully Sign Up!!!");
              clearComponent();
               pnlSign.hide();
               pnllogin.show();
          }     
             
          
          
         
    }//GEN-LAST:event_btnssigninActionPerformed
    
    public void clearComponent(){
        txtsuser.setText("");
        txtsemail.setText("");
        txtscontact.setText("");
        txtspass.setText("");
        txtsuser.requestFocus();
    }
    
    private void txtUserNameloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUserNameloginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUserNameloginActionPerformed

   
    private void btnsignupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsignupActionPerformed
        // TODO add your handling code here:
        //txtsuser.setText("");
        //txtsemail.setText("");
        //txtscontact.setText("");
        //txtspass.setText("");
        pnlSign.show();
        pnllogin.hide();
    }//GEN-LAST:event_btnsignupActionPerformed

    private void txtPasswordloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordloginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordloginActionPerformed

    private void btlloginclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btlloginclearActionPerformed
        // TODO add your handling code here:
       txtUserNamelogin.setText("");
       txtPasswordlogin.setText("");
    }//GEN-LAST:event_btlloginclearActionPerformed

    private void btncancelsignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelsignActionPerformed
        // TODO add your handling code here:
         pnlSign.hide();
        pnllogin.show();
    }//GEN-LAST:event_btncancelsignActionPerformed

    private void btnlogin1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlogin1ActionPerformed
        
         // int p = JOptionPane.showConfirmDialog(null, "Are you sure you want to delete record?","Delete",JOptionPane.YES_NO_OPTION);
          //if(p==0){
                        if(txtUserNamelogin.getText().toString().isEmpty()){
                      JOptionPane.showMessageDialog(pnllogin, "Please Enter Username!!!");
                  } 
                  else if(txtPasswordlogin.getText().toString().isEmpty()){
                      JOptionPane.showMessageDialog(pnllogin, "Please Enter Password!!!");
                  } 
                  else {
                    try {
                          c.Select("SELECT * FROM `sign_up` WHERE `username`='"+txtUserNamelogin.getText()+"' AND `password`='"+txtPasswordlogin.getText()+"'");
                          if(c.rs.next())
                                {
                            JOptionPane.showMessageDialog(null,"Login Successfully...!");
                            new FrmDashboard().setVisible(true);
                            this.dispose();
                            clearComponent1();
                        }
                        else
                        {
                            JOptionPane.showMessageDialog(null,"Invalid User");
                        }

                      }catch (SQLException ex) {
                        Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    clearComponent1();
                  }
       // }
           
    }//GEN-LAST:event_btnlogin1ActionPerformed
     public void clearComponent1(){
        txtUserNamelogin.setText("");
        txtPasswordlogin.setText("");
        txtUserNamelogin.requestFocus();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btlloginclear;
    private javax.swing.JButton btncancelsign;
    private javax.swing.JButton btnlogin1;
    private javax.swing.JButton btnsignup;
    private javax.swing.JButton btnssignin;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lalclgimg;
    private javax.swing.JLabel lblclosedlogin;
    private javax.swing.JLabel lbllogin;
    private javax.swing.JLabel lblloginbtn;
    private javax.swing.JLabel lblpasswordlogin;
    private javax.swing.JLabel lblscontact;
    private javax.swing.JLabel lblscross;
    private javax.swing.JLabel lblsemail;
    private javax.swing.JLabel lblsignup;
    private javax.swing.JLabel lblspass;
    private javax.swing.JLabel lblsusername;
    private javax.swing.JLabel lbluserlogin;
    private javax.swing.JLabel lblwellcome;
    private javax.swing.JPanel pnlSign;
    private javax.swing.JPanel pnllogin;
    private javax.swing.JPanel pnlwellcome;
    private javax.swing.JPasswordField txtPasswordlogin;
    private javax.swing.JTextField txtUserNamelogin;
    private javax.swing.JTextField txtscontact;
    private javax.swing.JTextField txtsemail;
    private javax.swing.JTextField txtspass;
    private javax.swing.JTextField txtsuser;
    // End of variables declaration//GEN-END:variables

    //private void clearComponent() {
      //  throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    //}
}
